SMTorg/smt

.gitignore, .travis.yml, README.md, appveyor.yml, setup.py, smt/extensions/tests/test_moe.py, smt/sampling_methods/lhs.py, smt/surrogate_models/krg_based.py, smt/utils/kriging_utils.py
- Use pyDOE2 instead of pyDOE
- Fix python 3 compatibility
- Activate Travis and Appveyor on Python 3.6
=> PyDOE2 and Python 3 compatibility

.travis.yml
The travis configuration was incorrect, we always tested against python 2.7. Anaconda is required to get tests under osx with Python 3.
=> fix travis python 3 config

smt/extensions/tests/test_mfk.py, smt/extensions/tests/test_moe.py, smt/problems/tests/test_problem_examples.py
When using testflo, matplotlib plotting should be disable. (see #135)
To do that <code>matplotlib.use('Agg')</code> has to be called as soon as matplotlib is imported.
This PR fixes that for moe and mfk.
However, I had to add the following line : 
<code>matplotlib.pyplot.switch_backend('Agg')</code>
at the beginning of <code>smt/problems/tests/test_problem_examples.py</code> to make it work on linux.
Weirdly on windows, the problem does not show up even without that PR.
=> matplotlib.use(Agg) first

smt/extensions/mfk.py, smt/surrogate_models/gekpls.py, smt/surrogate_models/kpls.py, smt/surrogate_models/kplsk.py, smt/surrogate_models/krg.py, smt/surrogate_models/krg_based.py, smt/utils/silence.py
It is achieved by making correlation and regression function options an enumerate. Fixes #153
=> Make kriging surrogate picklable

smt/surrogate_models/krg_based.py
The correlation function was not correctly called in the variance prediction of Kriging-based surrogate models: the function call was done on the option value directly, which is a str, resulting in a TypeError exception.
=> Correlation bug fix in variance prediction

.travis.yml
as miniconda 2 install seems to fail on osx 
<pre>
$ if [ "$TRAVIS_OS_NAME" = "osx" ]; then if [ "$PY" = "2.7" ]; then wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; fi else if [ "$PY" = "2.7" ]; then wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi fi
install.2
17.99s$ bash miniconda.sh -b -p $HOME/miniconda
install.3
0.01s$ export PATH="$HOME/miniconda/bin:$PATH"
install.4
0.01s$ hash -r
install.5
0.24s$ conda config --set always_yes yes --set changeps1 no
install.6
26.96s$ conda update -q conda
0.74s$ …
=> allow py2.7 failures on osx

smt/applications/ego.py, smt/applications/tests/test_ego.py, smt/surrogate_models/krg_based.py, smt/surrogate_models/tests/test_krg_based.py
@Paul-Saves, @NatOnera, I 've refactored the code to leverage numpy computations. 
I've just adapted assign_labels (to be renamed now): for categorical values it returns the index instead of the value (ex. for ["blue", "red", "green"] it assigns 0 for "blue" 1 for "red" and 2 for "green") in order to avoid manipulating a ndarray with strings.
By the way, I think we can go further in refactoring as these methods do not really belong to kriging surrogate per se, they could be isolated in another class. I will work on that in another PR.
=> Refactor relaxation methods using numpy capabilities

doc/_src_docs/applications/ego.rstx, smt/applications/ego.py, smt/applications/mixed_integer.py, smt/applications/tests/test_ego.py, smt/applications/tests/test_mixed_integer.py
In this PR:
- fix a bug in <code>fold_with_enum_index</code> ( 0, 0, 1  -> 2)
- add opposite function <code>unfold_with_enum_mask</code> (2 -> 0, 0, 1)
- fix <code>MixedIntegerSampling</code> and add <code>output_in_folded_space</code> option to control if created doe is folded (default) or not. 
- fix <code>MixedIntegerSurrogate</code> and add <code>input_in_folded_space</code> option to x to predict is expected to be folded (default) or not.
- fix <code>MixedIntegerContext</code> to add <code>work_in_folded_space</code> option allowing to build sampling and surrogate accordingly.
- fix <code>EGO</code> to use <code>MixedIntegerContext</code> with <code>work_in_folded_space</code> set to false
=> Fix and improve mixed integer module

smt/applications/moe.py, smt/applications/tests/test_moe.py
This PR adds the ability to select experts involved in the mixture:
* `allow` option to pass a list of expert names to be part of the mixture
* `deny` option to pass a list of expert names to exclude them
The following properties are added:
* `MOE.AVAILABLE_EXPERTS` class constant listing all the available expert names
* `moe.enabled_experts` lists the names of experts selected after initialization once allow/deny and derivatives/variances support options are taken into account.
=> MOE: add allow/deny options to enable experts being part of the mixture

smt/sampling_methods/full_factorial.py, smt/sampling_methods/lhs.py, smt/sampling_methods/random.py, smt/sampling_methods/sampling_method.py, smt/utils/misc.py
The \_\_call\_\_ method does scale the result from _compute() by default. This is unexpected and not documented. Also, it does prevent subclasses to generate samples in the input space directly.
=> Do not scale the samples by default

.github/workflows/tests.yml, .github/workflows/tests_coverage.yml, smt/applications/tests/test_ego.py
* Remove Python 3.6 from CI tests as it has reached its EOL
* Test EGO/GEKPLS with seeds to avoid random crash in svd call on MacOS
=> CI maintainance

AUTHORS.md, smt/applications/ego.py, smt/applications/tests/test_ego.py
Fix for  PR #340. `EI()` Now correctly identifies the optimal design vector from `y_data`
=> Fix EI to work with 2D `y_data` as used in GEKPLS

smt/applications/ego.py, smt/applications/moe.py, smt/applications/tests/test_ego.py, smt/applications/tests/test_moe.py
This PR fixes a bug related to wrong test data usage to determine best models when test data are specifiedvia `xtest`, `ytest` options. Moreover, a `ctest` option to specify test derivatives outputs is added to be consistent.
=> Fix moe when test data are specified

smt/surrogate_models/krg_based.py
Currently for KRG models, warning messages are printed. The user is unable to suppress the warnings using a warning filter.
**Changes**
The three printed warning messages are changed to warnings.warn(). This allows the user to suppress the warning message using a warning filter if necessary.
Warning is formatted to print only the message, same as before.
=> change warning message from print to warnings.warn()

.github/workflows/tests.yml, .github/workflows/tests_coverage.yml, doc/requirements.txt, requirements.txt, setup.py, smt/applications/mfk.py, smt/applications/mfkpls.py, smt/surrogate_models/kpls.py, smt/utils/kriging_utils.py
=> Dependencies cleanup

smt/applications/tests/test_ego.py, smt/surrogate_models/krg_based.py, smt/surrogate_models/surrogate_model.py, smt/surrogate_models/tests/test_krg_outputs.py, smt/surrogate_models/tests/test_krg_predictions.py, smt/surrogate_models/tests/test_krg_training.py, smt/tests/test_array_outputs.py
**Update derivative predictions:**
- Add vectorization for predict_variance_derivatives 
- Add component-wise derivatives
- Fix predict_derivatives vectorization bug (#389)
- Add vectorization tests and update the other tests 
**_**Special thanks to Inês Cardoso_**
**Clean EGO:**
- Add tests for qEI criteria and for SBO in EGO 
- Add tests for tunneling in EGO
=> Update derivatives predictions for vectors inputs and clean EGO

smt/applications/ego.py, smt/applications/mixed_integer.py, smt/applications/tests/test_ego.py, smt/applications/tests/test_mixed_integer.py, smt/surrogate_models/krg_based.py, smt/surrogate_models/ls.py, smt/surrogate_models/qp.py, smt/utils/kriging_utils.py
- There was both an inconsistency for the data normalization within Gower distance and a problem as the data were not in [0,1] as intended.  
This PR correct this error by using directly the bounds of the variables (xlimits) and by doing a proper job to project the data into [0,1]^n. 
- The  Acquisition criterion was not maximized at all with Mixed-integer variables. Now, it is maximized from random starting points by CObyLA. 
Fix several bugs.
=> Correct Gower distance bouds inconsistency & EGO for mixed integer

.github/workflows/tests_coverage.yml, smt/applications/tests/test_ego.py, smt/sampling_methods/tests/test_lhs.py, smt/tests/test_all.py, smt/tests/test_high_dim.py
This PR to avoid running expensive tests by default to get feedback from CI more rapidly.
To run slow tests just set the environment variable `RUN_SLOW=1`.
CI is updated to run all tests only for coverage.
=> Skip expensive tests

doc/_src_docs/applications/mixed_integer.rstx, smt/applications/ego.py, smt/applications/mixed_integer.py, smt/applications/tests/test_ego.py, smt/applications/tests/test_mixed_integer.py, smt/examples/run_examples.py, smt/surrogate_models/__init__.py, smt/surrogate_models/gekpls.py, smt/surrogate_models/krg_based.py, smt/surrogate_models/tests/test_surrogate_model_examples.py, smt/tests/test_all.py, smt/tests/test_derivs.py, smt/tests/test_extrap.py, smt/tests/test_low_dim.py, smt/tests/test_output_derivs.py, smt/tests/test_training_derivs.py, smt/utils/kriging_utils.py, smt/utils/mixed_integer.py, smt/utils/test/test_kriging_utils.py
This PR refactors XSpecs to enforce consistency at construction time. 
It reworks the API of `MixedInteger` classes: `MixedIntegerSamplingMethod`, `MixedIntegerSurrogateModel`, `MixedIntegerKrigingModel` and `MixedIntegerContext`
=> Refactor XSpecs for stronger typing

smt/applications/ego.py, smt/applications/mixed_integer.py, smt/applications/tests/test_ego.py, smt/applications/tests/test_mixed_integer.py, smt/surrogate_models/__init__.py, smt/surrogate_models/krg_based.py, smt/surrogate_models/tests/test_surrogate_model_examples.py, smt/utils/kriging.py, smt/utils/mixed_integer.py, smt/utils/test/test_kriging_utils.py
=> Replace constants used for enumerations by native Python enums

smt/applications/tests/test_mixed_integer.py, smt/problems/tests/test_problem_examples.py, smt/surrogate_models/__init__.py, smt/surrogate_models/krg_based.py, smt/utils/kriging.py
Implement Hierarchical kernels with 2 options (ALG and ARC kernels)
`              
declare(
"hierarchical_kernel",
MixHrcKernelType.ALG_KERNEL,
values=[
MixHrcKernelType.ALG_KERNEL,
MixHrcKernelType.ARC_KERNEL,
],
desc="The kernel to use for mixed hierarchical inputs. Only for non continuous Kriging",
)
`
=> Implements the Arc-kernel for hierarchical variables

smt/utils/design_space.py, smt/utils/test/test_design_space.py
At the request of @NatOnera:
- Allows to pass a single design vector and decode categorical/ordinal variable values
- Allows to pass multiple design vectors (n x nx matrix) and decode multiple design vectors at once
=> Support value decoding for complete design vectors

smt/applications/ego.py, smt/applications/tests/test_ego.py, smt/surrogate_models/krg_based.py, smt/surrogate_models/tests/test_krg_predictions.py, smt/utils/kriging.py
- For EGO the default optimizer is SLSQP with 200 iterations at max for continuous variables.
Now, for EGO, the default optimizer is COBYLA with 200 iterations at max for mixed variables.
- For optimizing the Kriging likelihood, the maximal number of iterations is 10 times the number of hyperparameters with a minimum of 25 iterations.
- Now Numba is not used by default anymore but has become a facultative option that is given by the environment variable  USE_NUMBA_JIT.
=> speeding up EGO

smt/applications/ego.py, smt/applications/tests/test_ego.py
Now, the infill criterion optimization is always done with SLSQP as in SMT1.3. It converges hardly because mixed integer is non-smooth and quickly high-dimensional  but it is more fast and shows better performances like that. 
Maxiter is 200 for Continuous inputs and 300 for mixed integer inputs.  Still a mixed integer test case had to be relaxed to pass through the pytest framework.
=> Revert back from COBYLA to SLSQP in EGO optimizer with mixed variables

smt/applications/tests/test_ego.py
This PR fixes error due to [expired deprecation in numpy 1.25.0](https://github.com/numpy/numpy/pull/23019)
=> Fix for expired deprecation in numpy 1.25

README.md, doc/requirements.txt, requirements.txt, setup.py, smt/examples/multi_modal/run_genn_demo.py, smt/sampling_methods/lhs.py, smt/utils/kriging.py
pyDOE2 is not supported any more, use pyDOE3. See #470
=> Update pyDOE2 dependency to pyDOE3

smt/applications/mfk.py, smt/applications/tests/test_mfk_mfkpls_mixed.py
For the new capability of mixed-integer multi-fidelity Kriging by @RemyCharayron .
=> Update NestedLHS with design_space

.github/workflows/tests.yml, .github/workflows/tests_minimal.yml, smt/applications/tests/test_ego.py, smt/applications/tests/test_mixed_integer.py, smt/utils/design_space.py
Currently when  `ConfigSpace` not installed, `import smt.surrogate_models` fails.
This PR fixes this issue and add minimal installation tests in CI.
=> Fix import error when `ConfigSpace` not installed

smt/utils/design_space.py
The continuous part of a point was not converted to 'float' type when ConfigSpace was disabled. Found by Nathalie
=> fix design space without ConfigSpace

smt/applications/tests/test_mixed_integer.py, smt/utils/test/test_design_space.py
* `run_XXX` methods are expected to be inserted in documantation as code examples. Test assertion funcitons like `assertTrue` cannot be used here otherwise code insertion routine fails,
* only `test_XXX` methods are run by `pytest`
=> Fix doc build: remove test assertion from run method

setup.py, smt/utils/test/test_design_space.py, tutorial/NotebookRunTestCases_Paper_SMT_v2.ipynb
update tests for design_space, run notebook for next week smt2 paper release and update setup.py
=> Remove design_space future deprecations and update metadata

smt/applications/mfkpls.py, smt/applications/mfkplsk.py, smt/applications/mixed_integer.py, smt/applications/tests/test_vfm.py, smt/surrogate_models/gekpls.py, smt/surrogate_models/krg_based.py, smt/surrogate_models/sgp.py, smt/surrogate_models/tests/test_krg_het_noise.py, smt/tests/test_array_outputs.py, smt/tests/test_kpls_auto.py
Two optimizers are available within Kriging: TNC that is gradient-based vs Cobyla that is gradient-free.
This PR fix TNC as a default optimizer whenever the derivative of the likelihood is available and Cobyla otherwise.
The distinction between where TNC is available and where it is not has been made more clear.
=> Clean internal optimization within Kriging

smt/applications/mixed_integer.py, smt/applications/moe.py, smt/applications/tests/test_ego.py, smt/applications/tests/test_mfk_mfkpls_mixed.py, smt/problems/robot_arm.py, smt/surrogate_models/tests/test_kpls.py, smt/utils/neural_net/model.py
This PR deals with some warnings raised with: 
* Python 3.8
* numpy 1.23.4, 
* scipy 1.10.1, 
* scikit-learn 1.3.1, 
* numba 0.57.0
* ConfigSpace 0.6.1
CI tests will present warnings triggered by more recent versions of those dependencies
=> Remove some warnings

smt/applications/mfk.py, smt/applications/mixed_integer.py, smt/applications/tests/test_mixed_integer.py, smt/surrogate_models/genn.py, smt/surrogate_models/krg_based.py, smt/surrogate_models/tests/test_surrogate_model_examples.py, smt/utils/design_space.py, smt/utils/test/test_design_space.py
- Remove scaling and normalization for categorical variables in MFK
- Ruff and black the code
- Fix several mixed integer tests that were badly setup 
- Add rounding in design_space for integer, ordinal or categorical variables
- Add a new ConfigSpace object (cs_vars_cate) that is fully categorical such that Integer and Ordinal Variables can take into account the design constraints defined in the original object (cs_vars). It ain't clean but it's a good workaround for now to deal with ConfigSpace 0.6.1.
- Add tests to check that Integer or Ordinal variables constraints are well taken into account!
=> Fix Ordinal and Integer constraints in DesignSpace

doc/_src_docs/surrogate_models/krg.rst, smt/applications/mixed_integer.py, smt/applications/tests/test_ego.py, smt/surrogate_models/krg.py, smt/surrogate_models/krg_based.py, smt/surrogate_models/tests/test_surrogate_model_examples.py, smt/tests/test_all.py, smt/utils/design_space.py
- Fix a bug in which the max bound was set to the max of the training database when normalizing data
- Fix a bug: ensure_design_space was not checking xlimits
- Update the documentation and add the sin exp kernel to the list of available kernels in KRG
=>  fix cliping predictions 

smt/applications/mfk.py, smt/applications/tests/test_ego.py, smt/applications/tests/test_mfk_variance.py, smt/applications/tests/test_mfkpls.py, smt/applications/tests/test_mfkplsk.py, smt/surrogate_models/krg_based.py, smt/surrogate_models/tests/test_krg_based.py, smt/surrogate_models/tests/test_surrogate_model_examples.py, smt/utils/design_space.py, smt/utils/neural_net/model.py, smt/utils/options_dictionary.py
- Fix a bug in which badly conditionned correlation matrix between the inputs (R) was not detected
- Add a test that display numerical problems with squar exp kernel
- Improve Ego test to be reproductible on differents operating systems
- Apply ruff 0.3.3
=> Add a warning and improve tests

.github/workflows/tests.yml, .github/workflows/tests_coverage.yml, .github/workflows/tests_minimal.yml, doc/requirements.txt, requirements.txt, setup.py, smt/surrogate_models/gpx.py, smt/surrogate_models/tests/test_gpx.py, smt/tests/test_all.py
This PR requires upgrading to `egobox` **0.18.0**.
=> Add derivatives prediction methods to GPX

smt/surrogate_models/krg_based.py, smt/surrogate_models/tests/test_kpls.py
KPLSK was slower than Kringing because of 3 problems:
- initialization of the parameters was done inside the loop (reinitialization between kpls and kriging)
- second optimization was done with multistart
- starting point for the second optimization may go a bit further than the bounds and was sometimes randomly reinitialized
Thanks to Lisa Pretsch
=> fix KPLSK performances

smt/utils/linear_solvers.py
=> Fix tol option deprecation in scipy solvers

smt/src/rmts/rmtc.cpp, smt/src/rmts/rmtc.hpp
In Issue #571, I encountered a bus error.
Using AddressSanitizer, I traced the error to a negative memory index caused by a 32 bit signed integer overflowing the bounds and requesting memory from a negative index.
Swap out `int` for `long` so that more total memory can be addressed and allow larger problem sizes.
=> Fix signed integer overflow

doc/_src_docs/surrogate_models/rmts.rst, smt/surrogate_models/tests/test_surrogate_model_examples.py
The documentation for RMTC uses `num_elements=20`. In Issue #574, it is shown that the training time is exponential in `num_elements`.
Hence using copy-paste from the example can blow up the compute time.
Reduce `num_elements` in the example so that users are less likely to hit this exponential behavior.
=> Document example with less expensive parameters

.github/workflows/tests.yml, .github/workflows/tests_minimal.yml, doc/requirements.txt, requirements.txt
This PR drops testing with py3.8 and starts testing with py3.12
=> Support for Python 3.12

.github/workflows/tests_coverage.yml
Following #575, this PR restores coverage test with ConfigSpace on python 3.11 and numpy 1.26.4.
=> Test with ConfigSpace on py3.11

smt/applications/ego.py, smt/applications/tests/test_ego.py, smt/surrogate_models/tests/test_krg_predictions.py
- Fix EI warning "divide by zero" that was raise because we devided by sigma before verifying it was not too small.
=> fix ei warning divide by zero

smt/surrogate_models/sgp.py, smt/surrogate_models/tests/test_sgp.py
This PR aims to enable the choice of the method for inducing points. It can either provide a set of induced points or directly specify the number of points to induce along with the method. As for the method, it can either induce points randomly or use the k-means method.
=> New methods to induce points in SGP

doc/_src_docs/applications/Mixed_Hier_surr.rst, doc/_src_docs/applications/Mixed_Hier_surr.rstx, smt/applications/tests/test_mixed_integer.py, smt/surrogate_models/krg_based.py
The correction was done twice for CR. Hence the GP model was not interpolating when using CR for decreed categorical variables.
=> fix CR and hier, twice corrected

doc/requirements.txt, requirements.txt, setup.py, smt/surrogate_models/gpx.py, smt/surrogate_models/tests/test_gpx.py
This PR adds save/load capability to GPX trained surrogate model (this feature relies on `egobox 0.23`).
```python
from smt.surrogate_models import GPX
gpx = GPX(...)
gpx.set_training_values(...)
gpx.train()
gpx.save("my_trained_gpx.json")  
gpx2 = GPX.load("my_trained_gpx.json")
```
=> Add save/load methods to GPX surrogate model

smt/applications/tests/test_ego.py, smt/applications/tests/test_mixed_integer.py, smt/design_space/__init__.py, smt/design_space/design_space.py, smt/design_space/tests/test_design_space.py
`smt` contains a standalone implementation `DesignSpace` but when the module `smt_design_space_ext` is installed it uses an enhanced implementation (based on `ConfigSpace` at the moment) allowing to manage hierarchical variables.
The constant `smt.design_space.HAS_DESIGN_SPACE_EXT` is automatically set (to `True`) when `smt_design_space_ext` is detected. It is only used for tests which results may vary depending on the design space implementation. 
Note: Normally we should not have to try to import from `smt_design_space_ext`. The `BaseDesignSpace` implementation (aka `smt.DesignSpace`, `smt_design_space_ext.DesignSpace` or `smt_design_space_ext.DesignSpaceGraph`) should be created by the user and pass to the `smt` code. This point should be addressed in an another PR later on.
=> Refactor `smt.design_space`

AUTHORS.md, smt/applications/tests/test_ego.py, smt/sampling_methods/lhs.py
Fix for issue #682 
- Updates comparison in LHS ese algorithm to allow it go into exploration mode
- Updates failed test cases which rely on the ese algorithm results
=> Fix to LHS ese comparison

smt/surrogate_models/krg_based.py, smt/surrogate_models/tests/test_krg_based.py
The surrogate API of SMT allows to pass several training data outputs as some surrogates are able to handle them. Currently kriging-based models happen to swallow such data and provide a surrogate but this resulting surrogate might not be as good as if we train a dedicated surrogate for each output (as only one set of hyperameters is actually optimized, the detailed impact of multiple outputs still has to be investigated).
As it was reported though with multiple outputs the resulting surrogate could be "good enough", this PR just adds a warning when `set_training_values()` is used with multiple outputs. Still such usage is not currently recommended (at least without checking the surrogate quality properly) and this warning might become a hard error in the future. 
This PR relates to #679
=> Add a warning on kriging-based surrogates being trained with multiple outputs

smt/surrogate_models/idw.py, smt/surrogate_models/rbf.py, smt/surrogate_models/rmtb.py, smt/surrogate_models/rmtc.py, smt/surrogate_models/rmts.py, smt/surrogate_models/tests/test_save_load.py
Add save / load functions to not train multiple time the surrogates using c++
=> Add save / load implementation for the surrogates using cpp (rbf, rmtb, rmtc, idw)

doc/_src_docs/dev_docs.rst, doc/_src_docs/dev_docs.rstx
This PR slightly modifies the documentation on how to build the documentation, clarifying that one must first install the packages listed in requirements.txt, and only after that, the ones in doc/requirements.txt
=> Update the documentation on how to build the documentation

doc/requirements.txt, requirements.txt, setup.py, smt/problems/torsion_vibration.py, smt/problems/water_flow.py, smt/problems/water_flow_lfidelity.py, smt/problems/welded_beam.py, smt/problems/wing_weight.py, smt/utils/misc.py
Since scipy 1.15, `derivative` function has been moved from `scipy.misc` to `scipy.differentiate`
Fixes #706
=> Handle scipy 1.15 changes related to `derivative` function used in benchmarking problems

.pre-commit-config.yaml
Add ruff linting and formatting configuration for pre-commit.
Basically, if pre-commit is not already installed, you have to:
1. `pip install pre-commit`
2. `pre-commit install`
then ruff linting and formatting will run automatically on commit.
See [pre-commit quickstart](https://pre-commit.com/#quick-start).
=> Add pre-commit hook for ruff

smt/surrogate_models/krg_based.py, smt/surrogate_models/tests/test_krg_predictions.py
This PR adds a "NoOp" value to the `hyper_opt` option of kriging-based surrogates, meaning there is actually no optimization done and the given theta0 value is used as the optimal hyperparameter value.
This setting is useful when the user wants to use predict methods with a given theta setting and avoiding the cost of the optimization.
=> Allow to disable hyperparameter optimization in kriging-based surrogates
