doc/RMTS.html
doc/RMTS.ipynb
doc/SMT.ipynb
doc/generate_options_table.py
examples/run_linux.py
examples/run_windows.py
smt/utils/options_dictionary.py

See RMTS.html for example output. The new file is called generate_options_table.py

Script to automatically generate options tables in docs

---

smt/src/rmts/rmtc.cpp
smt/src/rmts/rmts.cpp

fixes build on windows with vc14

Missing algorithm include for std::min/max

---

setup.py

Dont use -std=c++11 on windows

---

setup.py
smt/extensions/moe.py

This PR fixes some Python 3 compatibility issues in moe code.

Fix Python3 compatibility

---

.coveragerc
.gitignore
setup.cfg
setup.py

This PR to prepare packaging on Pypi: version number is bumped to 0.2.1.
coverage conf file is also added.

Pypi packaging

---

appveyor.yml

install testflo pypi release and remove unused nose, hdf5 dependencies

install numpy and scipy with pip

---

appveyor.yml
setup.py

Try to update pip before using it

Try to fix #113

---

smt/sampling_methods/lhs.py
smt/sampling_methods/tests/test_lhs.py

This PR fixes issue with lhs _ese raised by @RufoJ [here](https://github.com/SMTorg/smt/commit/5b8cd07167eca9d03256fc7b9368e64b8113137d#commitcomment-32286099)

fix pyDOE/pyDOE2 change

---

appveyor.yml

upgrade travis Mac OSX image 

---

smt/surrogate_models/krg_based.py

Also here, the str is trying to be called.

Similar bug in polynomial function

---

smt/surrogate_models/krg_based.py
smt/surrogate_models/tests/test_krg.py

fix predict_variances with more-than-one-dimensional output

---

smt/applications/tests/test_mfk.py
smt/applications/tests/test_vfm.py
smt/surrogate_models/tests/test_rmts.py
smt/tests/test_all.py
smt/tests/test_derivs.py
smt/utils/linear_solvers.py
smt/utils/neural_net/activation.py
smt/utils/neural_net/optimizer.py

* add test coverage for VFM
* move MFK tests in applications
* exclude some debug code from coverage
* cover line searches and linear solvers used by RTMS
* fixes #101

Improve test coverage

---

doc/_src_docs/applications/mfk.rstx
smt/applications/ego.py
smt/applications/tests/test_ego.py
smt/applications/tests/test_mfk.py

* add ydoe option
* add test_ydoe option
* doc fixes

add ydoe option

---

smt/applications/mfk.py
smt/applications/tests/test_mfk.py

* Create class `NestedLHS`
* Add test `test_nested_lhs` in `test_mfk.py`
* `run_mfk_example` edit to use the new class `NestedLHS`

Ft nested doe

---

.gitignore
smt/surrogate_models/krg_based.py
smt/surrogate_models/tests/test_krg.py

Fix kriging derivatives

---

smt/surrogate_models/kpls.py
smt/surrogate_models/kplsk.py
smt/surrogate_models/krg_based.py
smt/utils/kriging_utils.py

fix sklearn cross_decomposition module warning

---

smt/sampling_methods/full_factorial.py
smt/sampling_methods/tests/test_fullfactorial.py

fix weigths and clip options

---

smt/surrogate_models/krg_based.py
smt/surrogate_models/tests/test_krg.py

krg bug fix when poly=constant and ndim>2

---

smt/surrogate_models/qp.py

fix qp bug (run_example script)

---

smt/applications/mixed_integer.py
smt/applications/tests/test_mixed_integer.py

Fix in mixed_integer::unfold_with_enum_mask

fix unfold_with_enum_mask bug

---

smt/sampling_methods/lhs.py
smt/sampling_methods/tests/test_lhs.py

This PR adds the random_state option to LHS sampling method in order to control randomness for test repeatability (#250)

Add ramdom_state option to LHS

---

.coveragerc
.github/workflows/tests.yml
.github/workflows/tests_coverage.yml
.travis.yml
smt/applications/ego.py
smt/applications/tests/test_ego.py
smt/applications/tests/test_mixed_integer.py
smt/applications/tests/test_vfm.py
smt/examples/b777_engine/b777_engine.py
smt/examples/rans_crm_wing/rans_crm_wing.py
smt/surrogate_models/tests/test_krg_training.py
smt/tests/test_high_dim.py

This PR contains the following:
* add <code>random_state</code> option to EGO optimizer
* make some tests deterministic using np.random.RandomState
* suppress some matplotlib deprecation warnings
* prepare to switch from Travis to Github Actions (Travis does not seem to work very well any more for [open source projects]( https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works)

Tests cleanup

---

smt/applications/tests/test_vfm.py
smt/examples/run_examples.py
smt/surrogate_models/krg_based.py
smt/surrogate_models/tests/test_krg_training.py

Correct a bug in the bounds and add an example of noisy kriging

Correct a bug in the bounds and add an example of noisy kriging

---

smt/applications/moe.py
smt/applications/tests/test_vfm.py
smt/sampling_methods/sampling_method.py
smt/surrogate_models/krg_based.py
smt/surrogate_models/tests/test_krg_training.py
smt/surrogate_models/tests/test_surrogate_model_examples.py
smt/tests/test_array_outputs.py
smt/utils/kriging_utils.py

add a small multistart to avoid having too often really bad hyperparameters.

add a small multistart

---

.github/workflows/tests.yml
.github/workflows/tests_coverage.yml
smt/applications/mfk.py
smt/applications/mfkpls.py
smt/surrogate_models/kpls.py
smt/surrogate_models/krg_based.py
smt/surrogate_models/tests/test_kpls.py
smt/tests/test_all.py
smt/utils/kriging_utils.py

fixes #274 
Maybe we will have to review this workaround with scikit-learn 0.24.2. 
See also:
https://github.com/scikit-learn/scikit-learn/pull/19922

Fix sklearn 0.24 PLS

---

doc/_src_docs/surrogate_models.rst
doc/_src_docs/surrogate_models.rstx

Add doc section about saving and loading models

---

smt/applications/mixed_integer.py
smt/surrogate_models/krg_based.py
tutorial/SMT_Tutorial.ipynb

Fix a circular import in smt tutorial

fix bug in import

---

smt/applications/mfk.py
smt/applications/tests/test_mfk_1fidelity.py

This PR contains changes from #339 and adds automated tests

Fix MFK to get it work with one fidelity

---

smt/sampling_methods/lhs.py

fixes #350, maybe some development code leftover...

Remove LHS ese dead code

---

.github/workflows/tests.yml

Start testing with Python 3.10 on ubuntu

Tests with Python 3.10

---

smt/utils/krg_sampling_utils.py
smt/utils/test/test_kriging_sampling_utils.py

Add methods to sample a conditioned Gaussian Process with Cholesky decomposition, eigendecomposition and Karhunen-Loève decomposition based on Nyström method.

Add kriging sampling methods

---

smt/applications/ego.py
smt/applications/mixed_integer.py
smt/surrogate_models/ls.py
smt/surrogate_models/qp.py

Add data normalization in QP
xlimits is no longer a parameter of QP and LS
self.work_in_folded_space is now generalized and properly checked

Add data normalization in QP and clean QP, LS and EGO

---

doc/preprocess.py
setup.py
smt/surrogate_models/krg_based.py

This PR is just a polishing of the works done in the last 3 PR by Jasper, Paul and Rémi :)

Cleaning krg_based for categorical__kernel 

---

requirements.txt
smt/applications/tests/test_ego.py

* Set random seed for initial DOE build. Note: does not work with 42.
* Add numba to requirements to benefit from JIT compilation

Fix test reproducibility

---

tutorial/SMT_DesignSpace_example.ipynb
tutorial/SMT_MixedInteger_application.ipynb

Fix colab link

---

doc/_src_docs/applications/Mixed_Hier_usage.rst
doc/_src_docs/applications/Mixed_Hier_usage.rstx
smt/utils/design_space.py

... and fix sphinx design space examples rendering

Cleanup x type in documentation

---

smt/applications/ego.py
smt/applications/mixed_integer.py
smt/applications/tests/test_ego.py
smt/applications/tests/test_mixed_integer.py
smt/surrogate_models/krg_based.py
smt/utils/design_space.py
smt/utils/test/test_design_space.py

Fix a bug over options for Mixed Hierarchical Sampling 
Fix a rounding bug in  Mixed Hierarchical Sampling
Fix a sampling bug in EGO

Fix mixed hierarchical sampling

---

smt/surrogate_models/krg_based.py

When using SGP, this PR prevents from computing classic covariance matrix as the purpose of SGP is indeed to avoid memory space or computation time problems we may encounter with the full computation.

Avoid distances computation when using SGP

---

smt/applications/ego.py
smt/applications/mixed_integer.py
smt/applications/tests/test_ego.py
smt/applications/tests/test_mfk_mfkpls_mixed.py
smt/applications/tests/test_mixed_integer.py
smt/problems/tests/test_problem_examples.py
smt/utils/design_space.py
smt/utils/test/test_design_space.py

- Uniformize usage between design_space.sample_valid_x() andMixedIntegersampling _call__() 
- Separate RandomState & seed parameters : RandomState by default

Clean mixed integer sampling & seeding

---

smt/applications/mfk.py
smt/problems/ndim_step_function.py
smt/surrogate_models/krg_based.py
smt/surrogate_models/tests/test_surrogate_model_examples.py
smt/tests/test_all.py
smt/utils/kriging.py
smt/utils/neural_net/data.py

https://github.com/OpenMDAO/OpenMDAO/issues/2946

fix numba test in sbarchopt and remove numpy deprecation

---

smt/surrogate_models/krg_based.py

fix variance prediction for when y is > 100000 (error machine)

fix variance prediction

---

smt/applications/tests/test_mfk.py
smt/tests/test_all.py
smt/tests/test_high_dim.py

This PR removes/adjusts the most expensive tests to reduce overall execution time

Rework tests to reduce CI execution time

---

smt/applications/tests/test_mixed_integer.py
smt/surrogate_models/krg_based.py
smt/surrogate_models/tests/test_krg_predictions.py

- Add Mixed integer KPLSK for CR & GD kernels
@Paul-Saves
[update KPLSK mixed: krg_based & test. Add a boolean for testing second loop.

Add Mixed integer KPLSK

---

smt/surrogate_models/sgp.py
smt/surrogate_models/tests/test_krg_based.py

Update sgp for non-normalized data => Raise warnings and do not crash if the current tested theta is just unluckly too big

Update sgp for non-normalized data

---

smt/applications/moe.py
smt/applications/tests/test_save_load_moe_mfk.py
smt/surrogate_models/tests/test_save_load.py

Add save / load functions for those applications and a test

Add save / load functions for applications MOE, MFK, MFKPLS, MFKPLSK

---

AUTHORS.md
tutorial/README.md
tutorial/SBO/SMT_EGO_application.ipynb

Update the readme and correct a typo in EGO
Co-authored-by: heinehav < heine.rostum@gmail.com>
---------
Co-authored-by: heinehav < heine.rostum@gmail.com>

Update EGO notebook

---

doc/_src_docs/applications/Mixed_Hier_surr.rst
doc/_src_docs/applications/Mixed_Hier_usage.rst
doc/_src_docs/applications/Mixed_Hier_usage.rstx
doc/_src_docs/applications/cckrg.rst
doc/_src_docs/applications/cckrg.rstx
doc/_src_docs/applications/ego.rst
doc/_src_docs/applications/mfk.rst
doc/_src_docs/applications/mfkpls.rst
doc/_src_docs/applications/mfkplsk.rst
doc/_src_docs/applications/podi.rst
doc/_src_docs/applications/podi.rstx
doc/_src_docs/dev_docs/dev_design_space.rst
doc/_src_docs/dev_docs/dev_design_space.rstx
doc/_src_docs/surrogate_models.rst
doc/_src_docs/surrogate_models.rstx
doc/_src_docs/surrogate_models/gpr/gekpls.rst
doc/_src_docs/surrogate_models/gpr/gpx.rst
doc/_src_docs/surrogate_models/gpr/kpls.rst
doc/_src_docs/surrogate_models/gpr/kplsk.rst
doc/_src_docs/surrogate_models/gpr/krg.rst
doc/_src_docs/surrogate_models/gpr/krg.rstx
doc/_src_docs/surrogate_models/gpr/mgp.rst
doc/_src_docs/surrogate_models/gpr/sgp.rst
doc/requirements.txt
smt/design_space/design_space.py
smt/problems/problem.py
smt/surrogate_models/gpx.py
smt/surrogate_models/krg_based.py
smt/surrogate_models/surrogate_model.py

and fix sphinx documentation warnings

Add save/load API documentation

---

smt/surrogate_models/sgp.py
smt/surrogate_models/tests/test_krg_based.py
smt/surrogate_models/tests/test_sgp.py

Make SGP reproducible

---

.github/workflows/build_release.yml
.github/workflows/tests.yml
.github/workflows/tests_coverage.yml
.github/workflows/tests_minimal.yml
smt/__init__.py

... and prepare dropping Python 3.9 (EOL in October 2025)

Support Python 3.13
